### PR TITLE
add protocol scheme validation

### PR DESCRIPTION
**Pull request by gohumble**
Hey, 

this PR should improve URL protocol scheme and domain name validation for lnurl decode and encoding functions. 

# Description 
We noticed some unresolvable lnurls with `lnurlp://` encoded protocol schemes in our application. Those encoded lnurls get decoded using LNURLDecode before resolving the URL. The assumption that LNURLDecode always returns a resolvable plain-text https url was wrong. 
```go 
// LNURLDecode takes a bech32-encoded lnurl string and returns a plain-text HTTPS URL.
func LNURLDecode(code string) (string, error) {
```

## Example 

I thought `lnurl1d3h82unvwqaz7tmydakkz6twdesk6efwvdhk6ddysck` should be decoded to `https://domainname.com` but the result is `lnurlp://domainname.com`.
On the other hand, if you input `lnurlp://domainname.com` the scheme will be updated to `https` 

The only way of decoding `lnurl1d3h82unvwqaz7tmydakkz6twdesk6efwvdhk6ddysck` to `https://domainname.com` is by invoking the decode function twice.

## Solution 
Introducing strict encode and decode functions. Default encode and decode functions stay untouched to prevent any breaking changes. 

### Decoding 
Strict functions will always decode `hostnames and IP's as `HTTPS`. `.onion` links will be decoded and encoded with `http` protocol scheme. 
If the input is an invalid domain name / IP, the protocol scheme will **not** be added or updated. 

### Encoding 
Encoding a string will also ensure that the encoded lnurl includes the correct protocol scheme. 

### Validation 
The parser will also check if the TLD is "controlled" by ICANN. 
It is also able to handle puny code domain names. (see tests)

If any validation fails, the input string will still be encoded / decoded without any protocol scheme adjustments. This will also return an error and notify the user that the output is not a valid LNURL. 

I added 69 unit tests for default and strict encoders. If you don't like this proposal, feel free to include those for the default encoders only. 

## Testing 
+ TestLNURLDecodeStrict: testing strict decode function 
+ TestLNURLEncodeStrict: testing strict encode function
+ TestLNURLEncode: testing default encode function 
+ TestLNURLDecode: testing default decode function 
+ TestLNURLEncodeDecode: decode and encode multiple times 

### Results 
```
=== RUN   TestLNURLDecodeStrict
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gup69uhnzt339ccjuvf0wccj7mrww4exctmsv9usux0rql__ip_change_scheme
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7vfwxyhrzt339amrztmvde6hymp0wpshjr50pch__ip_keep_scheme
=== RUN   TestLNURLDecodeStrict/lnurl1d3h82unvwqaz7tmpwp5juenfv96x5ctx9e3k7mf0wccj7mrww4exctmsv9usxr8j98__change_scheme
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gurn8ghj77rw95khx7r3wc6kwv3nv3uhyvmpxserscfwvdhk6tmkxyhkcmn4wfkz7urp0y6jmn9j__puny
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gurn8ghjle443052l909sxr7t8ulukgg6tnrdakj7a339akxuatjdshhqctea4v3jm__puny2
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gup69uh7ddvtazhetevpsljel8l9jzxjummwd9hkutmkxyhkcmn4wfkz7urp0ygc52rr__puny_onion
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7er0d4skjm3wdahxjmmw9amrztmvde6hymp0wpshjcw5kvw__puny_onion
=== RUN   TestLNURLDecodeStrict/lnurl1d3h82unvjhypn2__string
=== RUN   TestLNURLDecodeStrict/LNURL1D3H82UNVJHYPN2__string_uppercase
=== RUN   TestLNURLDecodeStrict/https://lnurl.fiatjaf.com__httpsScheme
=== RUN   TestLNURLDecodeStrict/lnurlp://lnurl.fiatjaf.com__lnurlp
=== RUN   TestLNURLDecodeStrict/onion://lnurl.fiatjaf.onion__onion
=== RUN   TestLNURLDecodeStrict/lnurl1dahxjmmw8ghj7mrww4exctnxd9shg6npvchx7mnfdahquxueex__encoded_onion
=== RUN   TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7mrww4exctnxd9shg6npvchx7mnfdahq874q6e__encoded_https_onion
--- PASS: TestLNURLDecodeStrict (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gup69uhnzt339ccjuvf0wccj7mrww4exctmsv9usux0rql__ip_change_scheme (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7vfwxyhrzt339amrztmvde6hymp0wpshjr50pch__ip_keep_scheme (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1d3h82unvwqaz7tmpwp5juenfv96x5ctx9e3k7mf0wccj7mrww4exctmsv9usxr8j98__change_scheme (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gurn8ghj77rw95khx7r3wc6kwv3nv3uhyvmpxserscfwvdhk6tmkxyhkcmn4wfkz7urp0y6jmn9j__puny (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gurn8ghjle443052l909sxr7t8ulukgg6tnrdakj7a339akxuatjdshhqctea4v3jm__puny2 (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gup69uh7ddvtazhetevpsljel8l9jzxjummwd9hkutmkxyhkcmn4wfkz7urp0ygc52rr__puny_onion (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7er0d4skjm3wdahxjmmw9amrztmvde6hymp0wpshjcw5kvw__puny_onion (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1d3h82unvjhypn2__string (0.00s)
    --- PASS: TestLNURLDecodeStrict/LNURL1D3H82UNVJHYPN2__string_uppercase (0.00s)
    --- PASS: TestLNURLDecodeStrict/https://lnurl.fiatjaf.com__httpsScheme (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurlp://lnurl.fiatjaf.com__lnurlp (0.00s)
    --- PASS: TestLNURLDecodeStrict/onion://lnurl.fiatjaf.onion__onion (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dahxjmmw8ghj7mrww4exctnxd9shg6npvchx7mnfdahquxueex__encoded_onion (0.00s)
    --- PASS: TestLNURLDecodeStrict/lnurl1dp68gurn8ghj7mrww4exctnxd9shg6npvchx7mnfdahq874q6e__encoded_https_onion (0.00s)
=== RUN   TestLNURLEncodeStrict
=== RUN   TestLNURLEncodeStrict/http://看.com__punycode_change_scheme
=== RUN   TestLNURLEncodeStrict/http://看.com__punycode_keep_scheme
=== RUN   TestLNURLEncodeStrict/lnurlp://1.1.1.1:8080/v1/lnurl/pay__ip_and_port_change_scheme
=== RUN   TestLNURLEncodeStrict/lnurlp://1.1.1.1/v1/lnurl/pay__ip_change_scheme
=== RUN   TestLNURLEncodeStrict/lnurl.com.btc__invalid_tld_want_error
=== RUN   TestLNURLEncodeStrict/lnurl__invalid_domain_name
=== RUN   TestLNURLEncodeStrict/lnurl.msfmsdkfns&dfandfasdf__invalid
=== RUN   TestLNURLEncodeStrict/lnur%%%l__invalid_domain_name
=== RUN   TestLNURLEncodeStrict/lnurl__invalid_domain_name#01
=== RUN   TestLNURLEncodeStrict/lnur%%%l__invalid_domain_name#01
=== RUN   TestLNURLEncodeStrict/http://juhaavcaxhxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/__onion
=== RUN   TestLNURLEncodeStrict/lnurl.com.org__com.org
=== RUN   TestLNURLEncodeStrict/lnurl.com__com
=== RUN   TestLNURLEncodeStrict/lnurl.com.org__com.org#01
=== RUN   TestLNURLEncodeStrict/lnurl.com__com#01
=== RUN   TestLNURLEncodeStrict/lnurlp://api.fiatjaf.com/v2/lnurl/pay__lnurlp
=== RUN   TestLNURLEncodeStrict/lnurlp://api.fiatjaf.onion/v2/lnurl/pay__onion_lnurlp
=== RUN   TestLNURLEncodeStrict/https://api.fiatjaf.onion/v2/lnurl/pay__https_onion
=== RUN   TestLNURLEncodeStrict/http://api.fiatjaf.com/v2/lnurl/pay__http
--- PASS: TestLNURLEncodeStrict (0.00s)
    --- PASS: TestLNURLEncodeStrict/http://看.com__punycode_change_scheme (0.00s)
    --- PASS: TestLNURLEncodeStrict/http://看.com__punycode_keep_scheme (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurlp://1.1.1.1:8080/v1/lnurl/pay__ip_and_port_change_scheme (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurlp://1.1.1.1/v1/lnurl/pay__ip_change_scheme (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.com.btc__invalid_tld_want_error (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl__invalid_domain_name (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.msfmsdkfns&dfandfasdf__invalid (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnur%%%l__invalid_domain_name (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl__invalid_domain_name#01 (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnur%%%l__invalid_domain_name#01 (0.00s)
    --- PASS: TestLNURLEncodeStrict/http://juhaavcaxhxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/__onion (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.com.org__com.org (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.com__com (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.com.org__com.org#01 (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurl.com__com#01 (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurlp://api.fiatjaf.com/v2/lnurl/pay__lnurlp (0.00s)
    --- PASS: TestLNURLEncodeStrict/lnurlp://api.fiatjaf.onion/v2/lnurl/pay__onion_lnurlp (0.00s)
    --- PASS: TestLNURLEncodeStrict/https://api.fiatjaf.onion/v2/lnurl/pay__https_onion (0.00s)
    --- PASS: TestLNURLEncodeStrict/http://api.fiatjaf.com/v2/lnurl/pay__http (0.00s)
=== RUN   TestLNURLEncode
=== RUN   TestLNURLEncode/lnurl.com.orgs__invalid_tld_want_error
=== RUN   TestLNURLEncode/lnurl__invalid_domain_name
=== RUN   TestLNURLEncode/lnurl.msfmsdkfns&dfandfasdf__invalid
=== RUN   TestLNURLEncode/lnur%%%l__invalid_domain_name
=== RUN   TestLNURLEncode/lnurl__invalid_domain_name#01
=== RUN   TestLNURLEncode/lnur%%%l__invalid_domain_name#01
=== RUN   TestLNURLEncode/http://juhaavcaxhxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/__onion
=== RUN   TestLNURLEncode/lnurl.com.org__domain
=== RUN   TestLNURLEncode/lnurl.com__domain
=== RUN   TestLNURLEncode/lnurlp://api.fiatjaf.com/v2/lnurl/pay__lnurlp
=== RUN   TestLNURLEncode/lnurlp://api.fiatjaf.onion/v2/lnurl/pay__onion_lnurlp
=== RUN   TestLNURLEncode/https://api.fiatjaf.onion/v2/lnurl/pay__https_onion
=== RUN   TestLNURLEncode/http://api.fiatjaf.com/v2/lnurl/pay__http
--- PASS: TestLNURLEncode (0.00s)
    --- PASS: TestLNURLEncode/lnurl.com.orgs__invalid_tld_want_error (0.00s)
    --- PASS: TestLNURLEncode/lnurl__invalid_domain_name (0.00s)
    --- PASS: TestLNURLEncode/lnurl.msfmsdkfns&dfandfasdf__invalid (0.00s)
    --- PASS: TestLNURLEncode/lnur%%%l__invalid_domain_name (0.00s)
    --- PASS: TestLNURLEncode/lnurl__invalid_domain_name#01 (0.00s)
    --- PASS: TestLNURLEncode/lnur%%%l__invalid_domain_name#01 (0.00s)
    --- PASS: TestLNURLEncode/http://juhaavcaxhxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/__onion (0.00s)
    --- PASS: TestLNURLEncode/lnurl.com.org__domain (0.00s)
    --- PASS: TestLNURLEncode/lnurl.com__domain (0.00s)
    --- PASS: TestLNURLEncode/lnurlp://api.fiatjaf.com/v2/lnurl/pay__lnurlp (0.00s)
    --- PASS: TestLNURLEncode/lnurlp://api.fiatjaf.onion/v2/lnurl/pay__onion_lnurlp (0.00s)
    --- PASS: TestLNURLEncode/https://api.fiatjaf.onion/v2/lnurl/pay__https_onion (0.00s)
    --- PASS: TestLNURLEncode/http://api.fiatjaf.com/v2/lnurl/pay__http (0.00s)
=== RUN   TestLNURLDecode
=== RUN   TestLNURLDecode/onion://lnurl.fiatjaf.onion__onion
=== RUN   TestLNURLDecode/lnurl1d3h82unvwqaz7tmpwp5juenfv96x5ctx9e3k7mf0wccj7mrww4exctmsv9usxr8j98__change_scheme
=== RUN   TestLNURLDecode/lnurl1dp68gurn8ghj77rw95khx7r3wc6kwv3nv3uhyvmpxserscfwvdhk6tmkxyhkcmn4wfkz7urp0y6jmn9j__puny
=== RUN   TestLNURLDecode/lnurl1dp68gurn8ghjle443052l909sxr7t8ulukgg6tnrdakj7a339akxuatjdshhqctea4v3jm__puny2
=== RUN   TestLNURLDecode/lnurl1dp68gup69uh7ddvtazhetevpsljel8l9jzxjummwd9hkutmkxyhkcmn4wfkz7urp0ygc52rr__puny_onion
=== RUN   TestLNURLDecode/lnurl1dp68gurn8ghj7er0d4skjm3wdahxjmmw9amrztmvde6hymp0wpshjcw5kvw__domain_onion
=== RUN   TestLNURLDecode/lnurl1d3h82unvjhypn2__string
=== RUN   TestLNURLDecode/LNURL1D3H82UNVJHYPN2__string_uppercase
=== RUN   TestLNURLDecode/https://lnurl.fiatjaf.com__httpsScheme
=== RUN   TestLNURLDecode/lnurlp://lnurl.fiatjaf.com__lnurlp
=== RUN   TestLNURLDecode/lnurl1dahxjmmw8ghj7mrww4exctnxd9shg6npvchx7mnfdahquxueex__encoded_onion
=== RUN   TestLNURLDecode/lnurl1dp68gurn8ghj7mrww4exctnxd9shg6npvchx7mnfdahq874q6e__encoded_https_onion
--- PASS: TestLNURLDecode (0.00s)
    --- PASS: TestLNURLDecode/onion://lnurl.fiatjaf.onion__onion (0.00s)
    --- PASS: TestLNURLDecode/lnurl1d3h82unvwqaz7tmpwp5juenfv96x5ctx9e3k7mf0wccj7mrww4exctmsv9usxr8j98__change_scheme (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dp68gurn8ghj77rw95khx7r3wc6kwv3nv3uhyvmpxserscfwvdhk6tmkxyhkcmn4wfkz7urp0y6jmn9j__puny (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dp68gurn8ghjle443052l909sxr7t8ulukgg6tnrdakj7a339akxuatjdshhqctea4v3jm__puny2 (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dp68gup69uh7ddvtazhetevpsljel8l9jzxjummwd9hkutmkxyhkcmn4wfkz7urp0ygc52rr__puny_onion (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dp68gurn8ghj7er0d4skjm3wdahxjmmw9amrztmvde6hymp0wpshjcw5kvw__domain_onion (0.00s)
    --- PASS: TestLNURLDecode/lnurl1d3h82unvjhypn2__string (0.00s)
    --- PASS: TestLNURLDecode/LNURL1D3H82UNVJHYPN2__string_uppercase (0.00s)
    --- PASS: TestLNURLDecode/https://lnurl.fiatjaf.com__httpsScheme (0.00s)
    --- PASS: TestLNURLDecode/lnurlp://lnurl.fiatjaf.com__lnurlp (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dahxjmmw8ghj7mrww4exctnxd9shg6npvchx7mnfdahquxueex__encoded_onion (0.00s)
    --- PASS: TestLNURLDecode/lnurl1dp68gurn8ghj7mrww4exctnxd9shg6npvchx7mnfdahq874q6e__encoded_https_onion (0.00s)
=== RUN   TestLNURLEncodeDecode
=== RUN   TestLNURLEncodeDecode/__no_scheme_onion
=== RUN   TestLNURLEncodeDecode/__https
=== RUN   TestLNURLEncodeDecode/__https_scheme
=== RUN   TestLNURLEncodeDecode/__lnurlp
=== RUN   TestLNURLEncodeDecode/__no_scheme_com
=== RUN   TestLNURLEncodeDecode/__no_domain_string
--- PASS: TestLNURLEncodeDecode (0.00s)
    --- PASS: TestLNURLEncodeDecode/__no_scheme_onion (0.00s)
    --- PASS: TestLNURLEncodeDecode/__https (0.00s)
    --- PASS: TestLNURLEncodeDecode/__https_scheme (0.00s)
    --- PASS: TestLNURLEncodeDecode/__lnurlp (0.00s)
    --- PASS: TestLNURLEncodeDecode/__no_scheme_com (0.00s)
    --- PASS: TestLNURLEncodeDecode/__no_domain_string (0.00s)
PASS
```

### CODE REVIEW

**Comment by gohumble** [comment]
TODO: Probably add another function `HandleLNURLStrict`

**Comment by fiatjaf** [comment]
Are you saying that strict decode will decode `lnurl1d3h82unvwqaz7tmydakkz6twdesk6efwvdhk6ddysck` into a `https://` URL, bypassing the `lnurlp://`?

**Comment by fiatjaf** [comment]
Aside from that this PR looks good and well done. Maybe we should actually replace the default encoders for the strict ones? What are the risks?

**Comment by gohumble** [comment]
yes, it will bypass `lnurlp://`, because it is not a valid bech32 lnurl scheme. 
This makes sense. I didn't mean to change the protocol. Just wanted to increase the fault tolerance for this lib. 
Suddenly I don't think that switching to strict encoders is a good idea because: 
1. it will probably slow down the migration to LUD-17. 
2. it will return an error if the input is not a valid lnurl. This is a breaking change.

**Comment by fiatjaf** [comment]
Wait, no, returning an error is a good thing!

**Comment by gohumble** [comment]
I can solve `slow down the migration to LUD-17.` by taking the LUD-17 specification more into account. let me rethink and rewrite some tests and propose a new solution for this.

**Pull request closed without merging**
